/* ===================== ROSTER: 8 original opponents (art + stats + moves + lines) ===================== */
// defense table: which defenses avoid each attack kind; block = fraction of damage still taken (1 = unblockable)
const DEF = {
  jab: { dodge: 1, duck: 1, block: 0.2, hint: 'DODGE / DUCK / BLOCK' },
  hook: { dodge: 1, duck: 1, block: 0.35, hint: 'DODGE / DUCK' },
  upper: { dodge: 1, duck: 0, block: 0.45, hint: 'DODGE! (NO DUCK)' },
  body: { dodge: 1, duck: 0, block: 0.25, hint: 'DODGE / BLOCK' },
  lowkick: { dodge: 1, duck: 0, block: 0.3, hint: 'DODGE / BLOCK' },
  highkick: { dodge: 0, duck: 1, block: 0.55, hint: 'DUCK!' },
  haymaker: { dodge: 1, duck: 1, block: 1, hint: 'DODGE / DUCK - NO BLOCK!' },
  rocket: { dodge: 1, duck: 0, block: 1, hint: 'DODGE ONLY!' },
  laser: { dodge: 0, duck: 1, block: 1, hint: 'DUCK ONLY!' },
};
const M = (kind, side, name, dmg, tell, extra) => Object.assign({ kind, side, name, dmg, tell, interrupt: kind === 'jab' || kind === 'hook' || kind === 'body' || kind === 'upper' }, extra || {});
const GENERIC_CORNER = [
  "Drink some water. No, not that, that's my spit bucket.",
  "Remember what I taught ya: hit them, don't get hit. That's literally the whole sport.",
  "If you win, I'm buying. If you lose, you're buying. Also you're walking home.",
  "I been doin' this forty years. Forty! You know how many of my fighters won? Don't answer that.",
  "Dodge first, THEN punch. Punchin' first is how I lost my teeth. Both of 'em.",
  "Stars come from counters, kid. Make 'em miss, then make 'em pay.",
  "Kicks hit like a truck but they burn your hearts. Spend 'em wisely.",
  "Watch for the TWINKLE on the glove. That's when it's comin'.",
];
// shared art bits
function capHat(hx, hy, u, c, brim = 1, text) { EH(hx, hy - 12 * u, 23 * u, 13 * u, '#000', true); EH(hx, hy - 12 * u, 22 * u, 12 * u, c, true); R(hx - 22 * u, hy - 13 * u, 44 * u, 3 * u, sh(c, -0.25)); if (brim) { EO(hx, hy - 11 * u, 26 * u * brim, 3.5 * u, sh(c, -0.15)); } if (text) TX(text, hx, hy - 21 * u, '#fff', 1, 0.5, null); }
const ROSTER = [
  { id: 'doug', name: 'DOUG "THE COUCH" MULLIGAN', short: 'DOUG', from: 'Aisle 9 of a Costco in Ohio', weight: '287 lbs of pure gravy', record: '0-0 (forgot to sign up before)', circuit: 'MINOR CIRCUIT', voice: 95, color: '#d02030',
    blurb: 'Out-of-shape fantasy-football dad in a too-small "#1 DAD" tank. Slow, sloppy, very sweaty.',
    C: { s: 1.0, skin: '#f4c9a8', shW: 32, waW: 27, belly: { rx: 31, ry: 22, y: 8 }, shorts: '#c8b07a', trim: '#8a7440', shoe: '#f2f2f2', sock: '#ffffff', glove: '#d02030', legR: 8, frown: true, brow: '#5a3a1a', browAlways: true,
      torso(o, lx, ly, shY, waY, shW, waW, ln, s) { PO([lx(-shW + 6 + ln), ly(shY + 2), lx(-shW + 14 + ln), ly(shY), lx(shW - 14 + ln), ly(shY), lx(shW - 6 + ln), ly(shY + 2), lx(shW - 2 + ln), ly(shY + 34), lx(-shW + 2 + ln), ly(shY + 34)], '#f8f8f0'); TX('#1 DAD', lx(ln), ly(shY + 14), '#d02030', 1, 0.5, null); E(lx(ln * 0.6 + 4), ly(waY - 4), 2, 1.5, '#b88'); R(lx(-shW + 10 + ln), ly(shY + 26), 6 * s, 3 * s, '#e0a050'); },
      shortsDeco(o, lx, ly, waY, hipY, tw) { R(lx(-tw + 2), ly(hipY), 9, 7, '#a89060'); R(lx(tw - 11), ly(hipY), 9, 7, '#a89060'); },
      hairFront(hx, hy, u, o) { PO([hx - 9 * u, hy + 7 * u, hx + 9 * u, hy + 7 * u, hx + 10 * u, hy + 10 * u, hx - 10 * u, hy + 10 * u], '#6a4020'); capHat(hx, hy, u, '#c81e2e', 1.05, 'DAD'); },
      nose(hx, hy, u) { EO(hx, hy + 4 * u, 3.5 * u, 3 * u, '#f0b090'); },
      faceUnder(hx, hy, u, o) { for (let i = 0; i < 14; i++) PX(hx + Math.cos(i * 0.45 + 0.3) * 17 * u, hy + 10 * u + Math.sin(i * 0.45 + 0.3) * 7 * u, '#b89080'); },
      prop(o, k, lx, ly, s) { const x = lx(o.pose.gr.x), y = ly(o.pose.gr.y); PO([x - 5 * s, y - 22 * s, x + 5 * s, y - 22 * s, x + 4 * s, y - 4 * s, x - 4 * s, y - 4 * s], '#ffffff'); R(x - 5 * s, y - 17 * s, 10 * s, 5 * s, '#d02030'); LN(x + 1, y - 22 * s, x + 4 * s, y - 32 * s, '#ff3b5c', 2); }
    },
    st: { hp: 90, tf: 1.45, gl: 0.46, idle: [1.6, 2.9], rec: 1.55, dmg: 0.75, comboLimit: 4, readP: 0.12, feint: 0, combo: 0, punish: 0, guard: { mid: 3, low: 1, open: 2, high: 1 }, taunt: 0.14 },
    moves: { jab: M('jab', 'R', 'Dad Jab', 9, 0.8), hook: M('hook', 'L', 'Lawnmower Hook', 12, 1.0), belly: M('body', 'L', 'Belly Bump', 10, 1.0), nacho: M('haymaker', 'R', 'Nacho Haymaker', 22, 1.6) },
    ai: { jab: 4, hook: 3, belly: 2, nacho: 2 }, combos: [],
    lines: {
      intro: ["I did a 5K once. Well, I drove past one."],
      taunt: ["Hold on, my fantasy team just lost.", "Is this gonna take long? Wings are half off till 9.", "I'm not out of shape. Round is a shape!", "My doctor said I need cardio. You're my cardio.", "Timeout! I gotta check the score."],
      hit: ["BOOM! Dad strength!", "That's for trampling my lawn!", "Taste the nacho fury!"],
      hurt: ["My back! Not the back!", "OW! I'm calling my lawyer! Well, my brother-in-law.", "I need a Gatorade! The blue one!"],
      down: ["I'm just... resting my eyes..."], win: ["Dad strength never loses! Now who's got the dip?"],
    },
    corner: ["He breathes like a broken accordion. Keep him movin'.", "When he raises that nacho arm, get OUT of the way. That's a family-size haymaker.", "Body shots, kid. There's a LOT of target down there.", "When he stops to check his phone, hit him. Twice. It's what his kids would want."],
    interview: [['chet', "Carey, that was CRAZY! You dismantled a man who was clearly built out of cheese dip!"], ['carey', "Honestly I feel bad. He offered me a hot wing between rounds."], ['barry', "Oh my GOODNESS! When she hit that belly I saw RIPPLES, baby! Ripples!"], ['chet', "Is it true he was checking his fantasy league during the second round?"], ['carey', "He was. He's in last place. In both."], ['barry', "Big Daddy's been hungry this whole fight. Somebody get me nachos!"]],
  },
  { id: 'chad', name: 'CHAD BROSWORTH', short: 'CHAD', from: "Venice Beach (his mom's garage)", weight: '205 lbs, 0% body fat, 100% bro', record: '14-0 in arm wrestling', circuit: 'MINOR CIRCUIT', voice: 125, color: '#ff4fd8',
    blurb: 'Spray-tanned gym bro who guards his pretty face and has never, ever done leg day.',
    C: { s: 1.04, skin: '#e8955a', shW: 39, waW: 18, legR: 4, shorts: '#ff4fd8', trim: '#111', shoe: '#7dff3b', glove: '#7dff3b', brow: '#3a2010', browAlways: true,
      torso(o, lx, ly, shY, waY, shW, waW, ln, s) { const c = '#b86a38'; LN(lx(ln), ly(shY + 6), lx(ln), ly(waY - 2), c); for (let i = 0; i < 3; i++) { LN(lx(-9 + ln), ly(shY + 30 + i * 8), lx(9 + ln), ly(shY + 30 + i * 8), c); } EH(lx(-12 + ln), ly(shY + 18), 13 * s, 9 * s, c, false); EH(lx(12 + ln), ly(shY + 18), 13 * s, 9 * s, c, false); for (let i = -6; i <= 6; i++) PX(lx(i * 2 + ln), ly(shY - 2 + Math.abs(i) * 0.6), '#ffd23f'); },
      hairFront(hx, hy, u, o, rx, ry) { const pts = [hx - rx, hy - ry * 0.35]; for (let i = 0; i <= 8; i++) { const x = hx - rx + i * rx / 4; pts.push(x, hy - ry * (i % 2 ? 1.25 : 0.82)); } pts.push(hx + rx, hy - ry * 0.35, hx + rx * 0.7, hy - ry * 0.65, hx - rx * 0.7, hy - ry * 0.65); PO(pts, '#4a2a12'); for (let i = 0; i < 4; i++) E(hx - rx * 0.75 + i * rx * 0.5, hy - ry * 1.1, 3 * u, 2 * u, '#ffe36a'); R(hx - 14 * u, hy - ry * 0.62, 28 * u, 4 * u, '#111'); E(hx - 7 * u, hy - ry * 0.55, 5 * u, 2.5 * u, '#3af'); E(hx + 7 * u, hy - ry * 0.55, 5 * u, 2.5 * u, '#3af'); },
      nose(hx, hy, u) { LN(hx, hy + 2 * u, hx + 2 * u, hy + 6 * u, '#a0582a'); },
      prop(o, k, lx, ly, s) { const x = lx(o.pose.gl.x), y = ly(o.pose.gl.y); PO([x - 4 * s, y - 20 * s, x + 4 * s, y - 20 * s, x + 4 * s, y - 4 * s, x - 4 * s, y - 4 * s], '#2a2a2a'); R(x - 4 * s, y - 14 * s, 8 * s, 4 * s, '#7dff3b'); }
    },
    st: { hp: 110, tf: 1.3, gl: 0.44, idle: [1.2, 2.4], rec: 1.3, dmg: 0.85, comboLimit: 3, readP: 0.25, feint: 0, combo: 0.15, punish: 0.12, guard: { high: 6, mid: 1 }, taunt: 0.13, legWeak: 1.6, faceGuard: true },
    moves: { jab: M('jab', 'L', 'Bro Jab', 9, 0.75), bicep: M('hook', 'R', 'Bicep Bomb', 14, 1.15), protein: M('upper', 'L', 'Protein Uppercut', 15, 1.1), body: M('body', 'R', 'Ab Crunch', 10, 0.9) },
    ai: { jab: 4, bicep: 3, protein: 2, body: 2 }, combos: [['jab', 'jab'], ['jab', 'bicep']],
    lines: {
      intro: ["Bro. Bro. BROOO. You're about to get absolutely swoled."],
      taunt: ["Do you even lift, bro?", "Hold up, lemme check my pump.", "My protein shake has more fight than you.", "Leg day? Never heard of her.", "This face is insured, bro. Don't touch it."],
      hit: ["Gains, bro!", "That's what 5AM gym sessions get you!", "Bro-tected!"],
      hurt: ["Not the abs! They're for Instagram!", "My legs! I didn't know I HAD those!", "Bro, that's not cool, bro!"],
      down: ["Tell my protein... I love it..."], win: ["Bro, that was sick. Follow me @ChadFlexxx."],
    },
    corner: ["He never trained legs. Those things are basically breadsticks. KICK 'EM!", "He guards that pretty face like it's a leased Lambo. So go to the body.", "When he kisses his bicep, he's about to throw it. Get outta the way.", "He flexes when he taunts. That's free real estate, sweetheart."],
    interview: [['chet', "Carey! That leg kick! Have you ever seen a man's entire personality collapse like that? CRAZY!"], ['carey', "He told me he skips leg day. I took it personally."], ['barry', "Big Daddy has to say it: his legs looked like two cocktail straws holdin' up a refrigerator!"], ['chet', "Chad says backstage he 'let you win for content.'"], ['carey', "Tell Chad the content is him crying on the mat."], ['barry', "Oh my goodness, he's still flexing on the stretcher!"]],
  },
  { id: 'nana', name: 'NANA KNUCKLES', short: 'NANA', from: 'Shady Pines Retirement Village, Florida', weight: '98 lbs (103 years young)', record: 'Outlived 4 husbands', circuit: 'MINOR CIRCUIT', voice: 230, color: '#b78fd6',
    blurb: 'A 103-year-old granny with lightning jabs, a deadly purse and dentures with a mind of their own.',
    C: { s: 0.88, skin: '#f7d9c8', shW: 27, waW: 24, belly: { rx: 22, ry: 14, y: 6 }, shorts: '#ff9ac8', trim: '#fff', shoe: '#ff8ac8', sock: '#e8c8b0', glove: '#ff7ab8', legR: 6, erx: 7, ery: 7.2, blush: true, brow: '#aaa',
      torso(o, lx, ly, shY, waY, shW, waW, ln, s) { PO([lx(-shW + ln), ly(shY + 4), lx(shW + ln), ly(shY + 4), lx(waW + 2 + ln * 0.5), ly(waY), lx(-waW - 2 + ln * 0.5), ly(waY)], '#b78fd6'); P([lx(-4 + ln), ly(shY + 2), lx(4 + ln), ly(shY + 2), lx(ln), ly(waY)], '#f7d9c8'); for (let i = 0; i < 4; i++) EO(lx(5 + ln), ly(shY + 14 + i * 10), 1.5 * s, 1.5 * s, '#fff'); for (let i = -5; i <= 5; i++) E(lx(i * 2.4 + ln), ly(shY + 2 + (25 - i * i) * 0.25), 1.4 * s, 1.4 * s, '#fffaf0'); E(lx(-14 + ln), ly(shY + 26), 5 * s, 4 * s, '#ff9ac8'); },
      hairBack(hx, hy, u) { EO(hx, hy - 20 * u, 13 * u, 10 * u, '#d8d8e0'); LN(hx - 14 * u, hy - 34 * u, hx + 4 * u, hy - 16 * u, '#c0a040', 2); LN(hx + 14 * u, hy - 34 * u, hx - 4 * u, hy - 16 * u, '#c0a040', 2); E(hx - 14 * u, hy - 34 * u, 2 * u, 2 * u, '#ff3b5c'); },
      hairFront(hx, hy, u, o, rx, ry) { EH(hx, hy - ry * 0.3, rx * 1.02, ry * 0.75, '#d8d8e0', true); for (let i = 0; i < 6; i++) E(hx - rx * 0.8 + i * rx * 0.32, hy - ry * 0.55, 4 * u, 3 * u, '#e8e8f0'); for (const sd of [-1, 1]) { const ex = hx + sd * 6.2 * u, ey = hy - 3 * u; for (let a = 0; a < 6.28; a += 0.3) PX(ex + Math.cos(a) * 8.5 * u, ey + Math.sin(a) * 8.5 * u, '#5a3a8a'); } LN(hx - 1.5 * u, hy - 3 * u, hx + 1.5 * u, hy - 3 * u, '#5a3a8a'); LN(hx - 18 * u, hy + 4 * u, hx - 14 * u, hy + 6 * u, '#d0a890'); LN(hx + 18 * u, hy + 4 * u, hx + 14 * u, hy + 6 * u, '#d0a890'); },
      nose(hx, hy, u) { EO(hx, hy + 5 * u, 2.5 * u, 2 * u, '#f0b8a8'); },
      prop(o, k, lx, ly, s) { const x = lx(o.pose.gl.x), y = ly(o.pose.gl.y); EO(x + 6 * s, y - 6 * s, 7 * s, 5 * s, '#ff7a3a'); LN(x - 4 * s, y - 16 * s, x + 12 * s, y, '#c0a040', 2); LN(x + 14 * s, y - 16 * s, x, y + 2 * s, '#c0a040', 2); }
    },
    st: { hp: 118, tf: 1.15, gl: 0.42, idle: [1.0, 2.0], rec: 1.15, dmg: 0.85, comboLimit: 3, readP: 0.25, feint: 0.05, combo: 0.3, punish: 0.2, guard: { mid: 2, high: 2, low: 1, open: 1 }, taunt: 0.11, evade: 0.18, dentures: true },
    moves: { jab: M('jab', 'L', 'Needle Jab', 8, 0.7), jab2: M('jab', 'R', 'Needle Jab', 8, 0.7), purse: M('hook', 'R', 'Purse Swing', 14, 1.05), chomp: M('haymaker', 'L', 'Denture Chomp', 18, 1.3), shin: M('lowkick', 'R', 'Orthopedic Shin Kick', 10, 0.95) },
    ai: { jab: 4, jab2: 3, purse: 3, chomp: 1, shin: 1 }, combos: [['jab', 'jab2', 'jab'], ['jab2', 'purse']],
    lines: {
      intro: ["Come here, sweetie. Nana's gonna knit you a body bag."],
      taunt: ["Back in my day we fought bears. For fun.", "You look hungry. Have a butterscotch. Then have a fist.", "I've had hip replacements tougher than you.", "Speak up, dear, I can't hear you losing.", "Nap time's at 3. You'll be asleep by 2."],
      hit: ["Respect your elders!", "That's for never calling!", "Ha! Still got it!"],
      hurt: ["My hip! My GOOD hip!", "You're in my will now. Under 'enemies.'", "Where'd my teeth go?!"],
      down: ["Wake me... when it's bingo..."], win: ["Now be a dear and help Nana out of the ring. And clean your room."],
    },
    corner: ["Don't let the cardigan fool ya. She hit me with that purse in '74 and I still hear bells.", "She's sneaky quick on the jabs. Block 'em, and make her pay when she swings that purse.", "If she lunges with the chomp, sidestep it. Do NOT let those dentures latch on.", "She dodges sometimes. Old people are slippery. Don't ask me how I know."],
    interview: [['chet', "Carey, you just beat up a 103-year-old woman on live television. How do you feel?"], ['carey', "She bit me, Chet. With her dentures. They were NOT in her mouth at the time."], ['barry', "I been in a lotta fights, but I never seen teeth fly that far without a mouth attached!"], ['chet', "She says she wants a rematch and your mom's phone number."], ['carey', "Both of those are a hard no."], ['barry', "Let me tell you something, baby: Nana's still scarier than my mother-in-law!"]],
  },
  { id: 'reggie', name: 'SIR REGINALD CRUMPET III', short: 'REGINALD', from: 'Upper Snobbington, England', weight: '160 lbs of inherited wealth', record: 'Undefeated in polite society', circuit: 'MAJOR CIRCUIT', voice: 150, color: '#5a2a8a',
    blurb: 'Snooty aristocrat with a monocle and top hat. Fakes you out constantly and stops for tea.',
    C: { s: 1.0, skin: '#ffe2d4', shW: 28, waW: 20, shorts: '#5a2a8a', trim: '#ffd23f', shoe: '#111', sock: '#ffffff', glove: '#f4f4f4', cuff: '#ffd23f', legR: 6, blush: true, brow: '#6a4a2a',
      torso(o, lx, ly, shY, waY, shW, waW, ln, s) { P([lx(-7 + ln), ly(shY - 6), lx(ln), ly(shY - 2), lx(-7 + ln), ly(shY + 2)], '#111'); P([lx(7 + ln), ly(shY - 6), lx(ln), ly(shY - 2), lx(7 + ln), ly(shY + 2)], '#111'); E(lx(ln), ly(shY - 2), 2 * s, 2 * s, '#300'); for (let i = 0; i < 5; i++) PX(lx(-6 + i * 3 + ln), ly(shY + 18 + (i % 2) * 2), '#a07050'); LN(lx(-shW + 8 + ln), ly(shY + 2), lx(-waW + 4 + ln), ly(waY), '#ffd23f'); LN(lx(shW - 8 + ln), ly(shY + 2), lx(waW - 4 + ln), ly(waY), '#ffd23f'); },
      hairFront(hx, hy, u, o, rx, ry) { P([hx, hy + 7 * u, hx - 14 * u, hy + 9 * u, hx - 19 * u, hy + 4 * u, hx - 16 * u, hy + 7 * u, hx - 10 * u, hy + 5 * u], '#6a4a2a'); P([hx, hy + 7 * u, hx + 14 * u, hy + 9 * u, hx + 19 * u, hy + 4 * u, hx + 16 * u, hy + 7 * u, hx + 10 * u, hy + 5 * u], '#6a4a2a');  R(hx - 15 * u, hy - ry - 30 * u, 30 * u, 30 * u, '#000'); R(hx - 14 * u, hy - ry - 29 * u, 28 * u, 29 * u, '#1a1a22'); R(hx - 14 * u, hy - ry - 6 * u, 28 * u, 4 * u, '#7a2aaa'); EO(hx, hy - ry + 1 * u, 22 * u, 3.5 * u, '#1a1a22'); E(hx - 8 * u, hy - ry - 22 * u, 2 * u, 5 * u, '#3a3a48');
        if (!(o.dmg.eyeR >= 2)) { const ex = hx + 6.2 * u, ey = hy - 3 * u; for (let a = 0; a < 6.28; a += 0.25) PX(ex + Math.cos(a) * 7.5 * u, ey + Math.sin(a) * 8 * u, '#e0b030'); LN(ex + 7 * u, ey + 3 * u, ex + 10 * u, ey + 22 * u, '#e0b030'); } },
      nose(hx, hy, u) { P([hx, hy - 1 * u, hx + 3 * u, hy + 6 * u, hx - 2 * u, hy + 6 * u], '#f5c4b0'); },
      prop(o, k, lx, ly, s) { const x = lx(o.pose.gr.x), y = ly(o.pose.gr.y); EO(x, y - 4 * s, 9 * s, 2 * s, '#fff'); PO([x - 5 * s, y - 13 * s, x + 5 * s, y - 13 * s, x + 4 * s, y - 5 * s, x - 4 * s, y - 5 * s], '#ffffff'); R(x - 4 * s, y - 11 * s, 8 * s, 2 * s, '#7ab0ff'); for (let i = 0; i < 3; i++) PX(x + Math.sin(T * 3 + i) * 2, y - 16 * s - i * 3, '#ddd'); }
    },
    st: { hp: 135, tf: 1.05, gl: 0.4, idle: [0.9, 1.8], rec: 1.0, dmg: 0.95, comboLimit: 2, readP: 0.35, feint: 0.32, combo: 0.22, punish: 0.3, guard: { high: 2, mid: 2, low: 2, open: 1 }, taunt: 0.1, guardSwap: 0.9 },
    moves: { jab: M('jab', 'L', "Gentleman's Jab", 10, 0.65), jab2: M('jab', 'R', "Gentleman's Jab", 10, 0.65), upper: M('upper', 'R', 'Crumpet Uppercut', 16, 0.95), boot: M('highkick', 'L', 'The Royal Boot', 18, 1.1), body: M('body', 'L', 'Pinky Poke', 10, 0.8) },
    ai: { jab: 3, jab2: 3, upper: 2, boot: 2, body: 2 }, combos: [['jab', 'jab2'], ['jab', 'upper'], ['jab2', 'boot']],
    lines: {
      intro: ["I say, a commoner! Do try not to bleed on my shoes, darling."],
      taunt: ["I've had crumpets with more fight in them.", "Pip pip! Was that a punch or a sneeze?", "One does not sweat. One glistens.", "Your technique is frightfully peasant.", "Tea time, old girl. Do wait."],
      hit: ["Jolly good!", "Ha! Marquess of Smackbury!", "Spiffing!"],
      hurt: ["My monocle! Do you know what that COST?!", "Good heavens, a bruise on a peerage!", "This is most UN-sporting!"],
      down: ["Tell Mumsy... I was... frightfully brave..."], win: ["Splendid. Someone fetch my butler, I've chipped a nail."],
    },
    corner: ["He fakes with that monocle twitch. Wait for the TWINKLE on the glove, then move.", "When he lifts that fancy boot, DUCK. Don't dodge, don't block. Duck.", "He stops for tea every round. Hit him while his pinky's out.", "He switches his guard a lot. Hit wherever his gloves AIN'T."],
    interview: [['chet', "Carey, the man brought a TEAPOT to a fistfight. It's entirely possible he's insane."], ['carey', "I hit him so hard his accent changed."], ['barry', "His monocle popped out and landed in his own tea! That's poetry, baby!"], ['chet', "He's demanding a duel at dawn."], ['carey', "Tell him I'll be asleep. Like he was."], ['barry', "Oh my goodness. Sir Reginald is now Sir Regi-FLAT!"]],
  },
  { id: 'kevin', name: 'LIVESTREAM KEVIN', short: 'KEVIN', from: "His parents' basement (Wi-Fi only)", weight: '170 lbs, 2.3M followers (mostly bots)', record: 'Undefeated in comment sections', circuit: 'MAJOR CIRCUIT', voice: 140, color: '#2ad4c8',
    blurb: 'Influencer who streams the whole fight. Blinds you with a ring light and reads chat mid-round.',
    C: { s: 1.0, skin: '#d1a07a', shW: 30, waW: 21, shorts: '#151515', trim: '#ff2fd0', shoe: '#f4f4f4', glove: '#ff8a1e', legR: 6.5, brow: '#2a1a10', browAlways: true,
      torso(o, lx, ly, shY, waY, shW, waW, ln, s) { PO([lx(-shW + 2 + ln), ly(shY + 2), lx(shW - 2 + ln), ly(shY + 2), lx(shW - 8 + ln), ly(shY + 30), lx(-shW + 8 + ln), ly(shY + 30)], '#2ad4c8'); EH(lx(ln), ly(shY + 2), 13 * s, 7 * s, '#1fa89e', true); TX('KEV', lx(ln), ly(shY + 12), '#fff', 1, 0.5, '#117'); for (let i = -4; i <= 4; i++) PX(lx(i * 2 + ln), ly(shY - 1 + Math.abs(i) * 0.5), '#ffd23f'); },
      hairFront(hx, hy, u, o, rx, ry) { EH(hx, hy - ry * 0.25, rx * 1.02, ry * 0.85, '#111', true); R(hx - rx * 0.8, hy - ry * 0.75, rx * 1.6, 4 * u, '#ff2fd0'); R(hx + rx * 0.2, hy - ry - 2 * u, rx * 1.0, 4 * u, '#222'); E(hx + rx, hy + 6 * u, 1.5 * u, 1.5 * u, '#ffd23f'); },
      faceUnder(hx, hy, u) { R(hx - 1 * u, hy + 15 * u, 3 * u, 3 * u, '#2a1a10'); },
      nose(hx, hy, u) { LN(hx - 1 * u, hy + 2 * u, hx + 1 * u, hy + 6 * u, '#a07050'); },
      prop(o, k, lx, ly, s) { const x = lx(o.pose.gr.x), y = ly(o.pose.gr.y); LN(x, y, x + 10 * s, y - 34 * s, '#888', 2); const px = x + 10 * s, py = y - 38 * s; R(px - 6 * s, py - 9 * s, 12 * s, 16 * s, '#000'); R(px - 5 * s, py - 8 * s, 10 * s, 14 * s, k === 'flash' ? '#fff' : '#3a6aff'); if (k === 'flash') { E(px, py, 16 * s, 16 * s, 'rgba(255,255,255,0.4)'); } else TX('LIVE', px, py - 2 * s, '#ff2a2a', 1, 0.5, null); }
    },
    st: { hp: 148, tf: 1.0, gl: 0.38, idle: [0.8, 1.7], rec: 0.95, dmg: 1.0, comboLimit: 3, readP: 0.35, feint: 0.12, combo: 0.35, punish: 0.3, guard: { mid: 3, high: 2, low: 1, open: 1 }, taunt: 0.17 },
    moves: { jab: M('jab', 'L', 'Clickbait Jab', 10, 0.65), stick: M('hook', 'R', 'Selfie-Stick Swat', 14, 0.95), flash: M('jab', 'R', 'Ring-Light Flash', 14, 1.15, { flash: true, interrupt: false }), kick: M('lowkick', 'L', 'Trending Kick', 11, 0.85), body: M('body', 'R', 'Sponsored Body Shot', 11, 0.85) },
    ai: { jab: 3, stick: 3, flash: 2, kick: 2, body: 2 }, combos: [['jab', 'jab', 'stick'], ['kick', 'stick']],
    lines: {
      intro: ["What's up Kev Army! Smash that like button while I smash this lady!"],
      taunt: ["Hold on, reading chat. 'Kevin you're so brave.' Thanks, Mom.", "This fight is sponsored by a game you've never heard of.", "Use code KEVIN for 10% off your hospital bill.", "Chat says you're mid.", "Wait, wait, I gotta get this angle."],
      hit: ["Clip it! CLIP IT!", "That's going in the thumbnail!", "Ratio'd!"],
      hurt: ["Chat, she's demonetizing my FACE!", "Ow! That's a strike on my channel!", "Delete that! DELETE THAT!"],
      down: ["Don't forget... to... subscribe..."], win: ["GG EZ. Link in bio."],
    },
    corner: ["That ring light thing blinds ya. When it flashes, the punch comes right after. Dodge on the sound!", "He stops to read his phone. That's free money, kid.", "He's got a glass jaw and a plastic personality. Hit the jaw.", "Three in a row: jab, jab, swat. Wait it out, then counter."],
    interview: [['chet', "Carey! Kevin had two million people watching and they all saw you take his soul!"], ['carey', "Most of them were bots. The bots were cheering for me."], ['barry', "Kevin went down so hard his phone kept streaming the ceiling! Oh my goodness!"], ['chet', "His chat is spamming the letter 'L' right now. What's that mean?"], ['carey', "It means Kevin, Chet. It just means Kevin."], ['barry', "Smash that like button, baby! Big Daddy's subscribing to CAREY!"]],
  },
  { id: 'bjorn', name: 'BJORN "THE GLACIER" FROSTBEARD', short: 'BJORN', from: "A fjord you can't pronounce", weight: '390 lbs of frozen fury', record: '37 pillages, 0 losses', circuit: 'MAJOR CIRCUIT', voice: 70, color: '#ff7a2a',
    blurb: 'A gigantic Viking who shrugs off your punches mid-windup. Huge hits, huge health, huge beard.',
    C: { s: 1.14, skin: '#f2c4a8', shW: 36, waW: 30, belly: { rx: 30, ry: 20, y: 6 }, shorts: '#7a5030', trim: '#c8a070', shoe: '#5a3a1a', sock: '#d8c0a0', glove: '#8a8f99', legR: 8.5, ery: 6, erx: 5.5, my: 13, brow: '#c0501a', browAlways: true,
      torso(o, lx, ly, shY, waY, shW, waW, ln, s) { for (let i = 0; i < 26; i++) { const a = i * 2.4; PX(lx(Math.cos(a) * (6 + i * 0.5) + ln), ly(shY + 16 + Math.sin(a) * 6 + i * 0.4), '#c0501a'); } LN(lx(-shW + 6 + ln), ly(shY + 2), lx(shW - 10 + ln), ly(waY - 4), '#5a3a1a', 3); },
      shortsDeco(o, lx, ly, waY, hipY, tw) { for (let i = 0; i < 6; i++) E(lx(-tw + 5 + i * tw * 0.36), ly(hipY + 2 + (i % 2) * 3), 2.5, 2, '#4a2a10'); },
      hairBack(hx, hy, u, o, rx, ry) { for (const sd of [-1, 1]) { const bx = hx + sd * rx * 0.9; PO([bx, hy - ry * 0.5, bx + sd * 16 * u, hy - ry * 1.2, bx + sd * 20 * u, hy - ry * 2.0, bx + sd * 10 * u, hy - ry * 1.3, bx - sd * 2 * u, hy - ry * 0.8], '#f4f0e0'); } },
      faceUnder(hx, hy, u, o) { const b = '#d8601e'; PO([hx - 22 * u, hy + 2 * u, hx + 22 * u, hy + 2 * u, hx + 20 * u, hy + 18 * u, hx + 8 * u, hy + 34 * u, hx, hy + 40 * u, hx - 8 * u, hy + 34 * u, hx - 20 * u, hy + 18 * u], b); for (let i = 0; i < 6; i++) LN(hx - 14 * u + i * 6 * u, hy + 10 * u, hx - 12 * u + i * 5 * u, hy + 28 * u, '#b04a14'); LIMBO(hx - 6 * u, hy + 34 * u, 2.5 * u, hx - 8 * u, hy + 46 * u, 2 * u, b); LIMBO(hx + 6 * u, hy + 34 * u, 2.5 * u, hx + 8 * u, hy + 46 * u, 2 * u, b); E(hx - 8 * u, hy + 44 * u, 2 * u, 1.5 * u, '#ffd23f'); E(hx + 8 * u, hy + 44 * u, 2 * u, 1.5 * u, '#ffd23f'); E(hx, hy + 4 * u, 12 * u, 3 * u, b); },
      hairFront(hx, hy, u, o, rx, ry) { EH(hx, hy - ry * 0.3, rx * 1.06, ry * 0.95, '#000', true); EH(hx, hy - ry * 0.3, rx * 1.02, ry * 0.9, '#9aa0aa', true); R(hx - rx, hy - ry * 0.4, rx * 2, 4 * u, '#6a707a'); R(hx - 2 * u, hy - ry * 0.4, 4 * u, 16 * u, '#6a707a'); for (let i = 0; i < 5; i++) E(hx - rx * 0.8 + i * rx * 0.4, hy - ry * 0.35, 1.2 * u, 1.2 * u, '#dde'); },
      nose(hx, hy, u) { EO(hx, hy + 4 * u, 4 * u, 3.5 * u, '#f0a888'); },
      prop(o, k, lx, ly, s) { const x = lx(o.pose.gr.x), y = ly(o.pose.gr.y); LIMBO(x, y - 4 * s, 2 * s, x + 4 * s, y - 18 * s, 2 * s, '#f4f0e0'); EO(x + 6 * s, y - 24 * s, 7 * s, 6 * s, '#b0601a'); }
    },
    st: { hp: 190, tf: 1.05, gl: 0.4, idle: [1.0, 1.9], rec: 1.0, dmg: 1.3, comboLimit: 2, readP: 0.4, feint: 0.08, combo: 0.2, punish: 0.35, guard: { mid: 3, high: 2, low: 1 }, taunt: 0.09, armor: true, checkKick: 0.4 },
    moves: { jab: M('jab', 'L', 'Herring Jab', 11, 0.7, { interrupt: false }), hammer: M('haymaker', 'R', 'Mjolnir Hammer', 26, 1.4), fjord: M('highkick', 'L', 'Fjord Kick', 22, 1.15), low: M('lowkick', 'R', 'Longship Low Kick', 14, 1.0), body: M('body', 'L', 'Mead Hall Body Blow', 15, 0.95, { interrupt: false }) },
    ai: { jab: 3, hammer: 2, fjord: 2, low: 2, body: 2 }, combos: [['jab', 'hammer'], ['low', 'fjord']],
    lines: {
      intro: ["BJORN WILL MAKE YOU INTO LUTEFISK!"],
      taunt: ["Bjorn has eaten bigger than you. For breakfast. With mead.", "In Valhalla they laugh at your tiny punches!", "Bjorn does not feel pain. Bjorn feels... HUNGRY!", "Come, little herring!", "Bjorn's beard has defeated three men."],
      hit: ["SKOL!", "HA! Like smashing a herring!", "BJORN SMASH! Bjorn also SMASH!"],
      hurt: ["You have angered the BEARD!", "OOF! Good punch! Bjorn respects! Bjorn still destroys!", "Bjorn's helmet! It cost four goats!"],
      down: ["Bjorn... sees Valhalla... it has... buffet..."], win: ["TONIGHT BJORN FEASTS! Bring the meatballs!"],
    },
    corner: ["He's slow but he hits like a dump truck full of dump trucks. Don't trade with him.", "You CAN'T stop his windups by punchin'. He don't flinch. Move first, THEN punch.", "When he lifts that big leg, DUCK. When he raises the hammer, step aside.", "He checks leg kicks sometimes. Go upstairs with the head kick when he's open."],
    interview: [['chet', "Carey, you knocked out a four-hundred-pound Viking! That was CRAZY! I need him on the podcast."], ['carey', "I've been hit by smaller cars, Chet."], ['barry', "When Bjorn fell, my snack table bounced! My nachos jumped, baby!"], ['chet', "He's asking for his helmet back. It's in the third row."], ['carey', "Finders keepers. Viking rules."], ['barry', "Let me tell you something: that man has a BEARD. And now he has a BRUISE."]],
  },
  { id: 'hurtz', name: 'DR. MOLAR HURTZ, D.D.S.', short: 'DR. HURTZ', from: 'A strip-mall dental office in New Jersey', weight: '180 lbs, zero bedside manner', record: 'Pulled 10,000 teeth (4,000 on purpose)', circuit: 'WORLD CIRCUIT', voice: 160, color: '#2aa6a0',
    blurb: 'Creepy dentist who throws lightning-fast four-hit combos and wants to collect your teeth.',
    C: { s: 1.04, skin: '#ecd6c0', shW: 29, waW: 21, shorts: '#2aa6a0', trim: '#fff', shoe: '#f0f0f0', sock: '#2aa6a0', glove: '#f0f8ff', cuff: '#7ab0ff', legR: 6.5, brow: '#888', browAlways: true, noMouth: true, mouthWhen: o => o.dmg.maskOff,
      torso(o, lx, ly, shY, waY, shW, waW, ln, s) { PO([lx(-shW + 1 + ln), ly(shY + 1), lx(shW - 1 + ln), ly(shY + 1), lx(waW + 1 + ln * 0.5), ly(waY), lx(-waW - 1 + ln * 0.5), ly(waY)], '#2aa6a0'); P([lx(-6 + ln), ly(shY + 1), lx(6 + ln), ly(shY + 1), lx(ln), ly(shY + 10)], '#ecd6c0'); const tx = lx(-12 + ln), ty = ly(shY + 18); EO(tx, ty, 4 * s, 4 * s, '#fff'); R(tx - 3 * s, ty + 2 * s, 2 * s, 4 * s, '#fff'); R(tx + 1 * s, ty + 2 * s, 2 * s, 4 * s, '#fff'); },
      hairFront(hx, hy, u, o, rx, ry, face) { for (const sd of [-1, 1]) { for (let i = 0; i < 4; i++) E(hx + sd * rx * 0.92, hy - ry * 0.25 + i * 3 * u, 4 * u, 3 * u, '#ccc'); }
        EO(hx, hy - ry * 0.62, 7 * u, 6 * u, '#cfd8e0', '#555'); E(hx, hy - ry * 0.62, 3.5 * u, 3 * u, (Math.sin(T * 6) > 0 || face === 'tell') ? '#fffbe0' : '#e8f0ff'); R(hx - rx, hy - ry * 0.62, rx * 2, 2 * u, '#444');
        if (!o.dmg.maskOff) { PO([hx - 15 * u, hy + 3 * u, hx + 15 * u, hy + 3 * u, hx + 13 * u, hy + 16 * u, hx, hy + 19 * u, hx - 13 * u, hy + 16 * u], '#9ad4f0'); for (let i = 0; i < 3; i++) LN(hx - 12 * u, hy + 7 * u + i * 3 * u, hx + 12 * u, hy + 7 * u + i * 3 * u, '#7ab8d8'); LN(hx - 15 * u, hy + 5 * u, hx - rx, hy + 1 * u, '#fff'); LN(hx + 15 * u, hy + 5 * u, hx + rx, hy + 1 * u, '#fff'); }
        else { PO([hx + 14 * u, hy + 6 * u, hx + 22 * u, hy + 8 * u, hx + 20 * u, hy + 18 * u, hx + 12 * u, hy + 16 * u], '#9ad4f0'); } },
      nose(hx, hy, u, o) { if (o.dmg.maskOff) P([hx, hy, hx + 3 * u, hy + 6 * u, hx - 3 * u, hy + 6 * u], '#e0b8a0'); },
      prop(o, k, lx, ly, s) { const x = lx(o.pose.gr.x), y = ly(o.pose.gr.y); LIMBO(x, y - 4 * s, 2 * s, x + 2 * s, y - 24 * s, 1.5 * s, '#cfd8e0'); R(x + 1 * s, y - 30 * s, 1, 6 * s, Math.sin(T * 50) > 0 ? '#fff' : '#888'); }
    },
    st: { hp: 182, tf: 0.86, gl: 0.34, idle: [0.6, 1.3], rec: 0.82, dmg: 1.1, comboLimit: 2, readP: 0.45, feint: 0.25, combo: 0.5, punish: 0.45, guard: { mid: 2, high: 2, low: 2 }, taunt: 0.08, guardSwap: 0.6 },
    moves: { jab: M('jab', 'L', 'Flossing Jab', 10, 0.55), jab2: M('jab', 'R', 'Flossing Jab', 10, 0.55), hook: M('hook', 'R', 'Plaque Attack', 13, 0.7), root: M('upper', 'L', 'Root Canal', 18, 0.8, { steal: true }), novo: M('body', 'R', 'Novocaine Body Shot', 12, 0.7), kick: M('lowkick', 'L', 'Bite-Wing Low Kick', 12, 0.75) },
    ai: { jab: 3, jab2: 3, hook: 2, root: 2, novo: 2, kick: 1 }, combos: [['jab', 'jab2', 'hook', 'root'], ['jab2', 'novo'], ['kick', 'hook', 'jab']],
    lines: {
      intro: ["Open wide, sweetheart! This won't hurt a bit. That's a lie."],
      taunt: ["Have you been flossing? I can TELL you haven't been flossing.", "Your teeth are beautiful. I want them.", "Rinse and spit. Oh wait, you're busy losing.", "This next part may pinch. And by pinch I mean break.", "No lollipop for you."],
      hit: ["Oops, that's a cavity!", "One for the collection!", "Say AHHH!"],
      hurt: ["MY HANDS! I have a 2 o'clock!", "Ow! That's going on your bill!", "My mask! My beautiful mask!"],
      down: ["I need... a second... opinion..."], win: ["I'll keep this molar as a souvenir. NEXT PATIENT!"],
    },
    corner: ["That creep throws four in a row. Stay on defense till he finishes, then go to town.", "When he yells 'open wide' sometimes it's a fake. Wait for the TWINKLE.", "Knock that mask off his face and he loses his nerve.", "Root Canal comes from low. Don't duck it — dodge it."],
    interview: [['chet', "Carey, that dentist was trying to collect your teeth! Is that even legal?"], ['carey', "Joke's on him. I flossed this morning."], ['barry', "Big Daddy hasn't been to the dentist in nine years, and after tonight I'm NEVER going!"], ['chet', "Dr. Hurtz says he's gonna send you a bill."], ['carey', "Tell him to send it to his insurance. He's gonna need some."], ['barry', "Oh my goodness, I think one of HIS teeth is in my soda!"]],
  },
  { id: 'gary', name: 'CYBER-GARY 3000', short: 'CYBER-GARY', from: 'A server farm in Silicon Valley', weight: '640 lbs of venture capital', record: 'Terms of Service: Undefeated', circuit: 'WORLD CIRCUIT', voice: 90, color: '#9aa7b4',
    blurb: 'The champ: a tech-bro robot that learns your patterns, fires rocket fists and laser eyes.',
    C: { s: 1.1, robot: true, skin: '#9aa7b4', shW: 34, waW: 24, shorts: '#1a1a22', trim: '#ffd23f', shoe: '#555a66', glove: '#e0202a', legC: '#7a8592', legR: 7, armC: '#8a96a4', my: 13,
      headShape(hx, hy, u, o, rx, ry) { PO([hx - rx, hy - ry * 0.8, hx - rx * 0.8, hy - ry, hx + rx * 0.8, hy - ry, hx + rx, hy - ry * 0.8, hx + rx, hy + ry * 0.8, hx + rx * 0.8, hy + ry, hx - rx * 0.8, hy + ry, hx - rx, hy + ry * 0.8], '#9aa7b4'); R(hx - rx, hy - ry, rx * 2, 3 * u, '#c0cad4'); for (const [a, b] of [[-0.85, -0.8], [0.85, -0.8], [-0.85, 0.8], [0.85, 0.8]]) if (!(o.dmg.teeth > 2 && a > 0 && b > 0)) EO(hx + a * rx, hy + b * ry, 1.4 * u, 1.4 * u, '#d8dee4'); LN(hx, hy - ry, hx + (o.dmg.lump > 1 ? 8 : 0) * u, hy - ry - 12 * u, '#555', 2); E(hx + (o.dmg.lump > 1 ? 8 : 0) * u, hy - ry - 13 * u, 2.5 * u, 2.5 * u, Math.sin(T * 5) > 0 ? '#ff2a2a' : '#600'); },
      eyesFn(hx, hy, u, o, face) { const D = o.dmg; R(hx - 19 * u, hy - 9 * u, 38 * u, 12 * u, '#000'); R(hx - 18 * u, hy - 8 * u, 36 * u, 10 * u, '#101820'); const c = face === 'tell' || face === 'angry' ? '#ffd23f' : face === 'hurt' || face === 'dizzy' ? '#ff6bff' : '#ff2a2a';
        if (face === 'ko') { TX('x', hx - 8 * u - 2, hy - 7 * u, c, 1, 0, null); TX('x', hx + 8 * u - 2, hy - 7 * u, c, 1, 0, null); }
        else if (face === 'dizzy' || (face === 'hurt' && Math.random() < 0.5)) { for (let i = 0; i < 5; i++) R(hx + rand(-16, 12) * u, hy + rand(-7, 0) * u, rand(2, 6) * u, 2 * u, c); }
        else for (const sd of [-1, 1]) { const w = face === 'laugh' || face === 'gloat' ? 3 : 7; R(hx + sd * 8 * u - w / 2 * u, hy - 5 * u + (face === 'laugh' ? 2 * u : 0), w * u, (face === 'laugh' ? 2 : 4) * u, c); R(hx + sd * 8 * u - w / 2 * u, hy - 5 * u, w * u, 1, '#fff8'); }
        const cr = D.eyeL + D.eyeR; for (let i = 0; i < cr; i++) LN(hx - 16 * u + i * 9 * u, hy - 8 * u, hx - 10 * u + i * 8 * u + (i % 2 ? 4 : -3) * u, hy + 1 * u, '#c8f0ff'); },
      faceUnder(hx, hy, u, o, face) { const op = face === 'hurt' || face === 'laugh' || face === 'yell' || face === 'gloat'; R(hx - 9 * u, hy + 8 * u, 18 * u, (op ? 8 : 5) * u, '#000'); for (let i = 0; i < 5; i++) R(hx - 8 * u + i * 3.6 * u, hy + 9 * u, 2 * u, (op ? 6 : 3) * u, Math.sin(T * 20 + i) > 0.3 && op ? '#ff2a2a' : '#444'); for (const sd of [-1, 1]) { const lv = sd < 0 ? o.dmg.cheekL : o.dmg.cheekR; for (let i = 0; i < lv; i++) EO(hx + sd * (12 + i * 2) * u, hy + (2 + i * 4) * u, (2 + i) * u, (1.5 + i * 0.7) * u, '#6a7480', '#4a5560'); } },
      noMouth: true,
      torso(o, lx, ly, shY, waY, shW, waW, ln, s) { R(lx(-14 + ln), ly(shY + 8), 28 * s, 22 * s, '#000'); R(lx(-13 + ln), ly(shY + 9), 26 * s, 20 * s, '#3a4450'); for (let i = 0; i < 4; i++) R(lx(-10 + i * 6 + ln), ly(shY + 12), 4 * s, 3 * s, (Math.floor(T * 4) + i) % 3 ? '#2aff7a' : '#0a3a1a'); TX('G3K', lx(ln), ly(shY + 19), '#7ef0ff', 1, 0.5, null); for (let i = 0; i < 4; i++) LN(lx(-shW + 6 + ln), ly(shY + 34 + i * 6), lx(shW - 6 + ln), ly(shY + 34 + i * 6), '#7a8592'); if (o.hp < o.maxHp * 0.5 && Math.random() < 0.15) spray(lx(rand(-20, 20) + ln), ly(shY + rand(10, 40)), 3, 'spark'); },
      shortsDeco(o, lx, ly, waY, hipY, tw) { TX('VC', lx(0), ly(hipY - 4), '#ffd23f', 1, 0.5, null); },
      prop(o, k, lx, ly, s, hx, hy) { if (k === 'update') { R(hx - 26 * s, hy - 48 * s, 52 * s, 12 * s, '#000'); R(hx - 25 * s, hy - 47 * s, 50 * s * clamp(o.stT / 3.2, 0, 1), 10 * s, '#2aff7a'); TX('UPDATING', hx, hy - 60 * s, '#7ef0ff', 1, 0.5); } else if (k === 'buffer') { for (let i = 0; i < 8; i++) { const a = T * 8 + i * 0.785; E(hx + Math.cos(a) * 12 * s, hy - 40 * s + Math.sin(a) * 12 * s, 2 * s, 2 * s, i === 0 ? '#fff' : '#7a8592'); } } }
    },
    st: { hp: 205, tf: 0.84, gl: 0.36, idle: [0.65, 1.35], rec: 0.8, dmg: 0.98, comboLimit: 2, readP: 0.5, feint: 0.3, combo: 0.5, punish: 0.5, guard: { mid: 2, high: 2, low: 2 }, taunt: 0.12, adapt: true, guardSwap: 0.7 },
    moves: { jab: M('jab', 'L', 'Binary Jab', 11, 0.55), jab2: M('jab', 'R', 'Binary Jab', 11, 0.55), hook: M('hook', 'L', 'Cloud Hook', 15, 0.75), upper: M('upper', 'R', 'Upper-Cut-and-Paste', 18, 0.85), rocket: M('rocket', 'R', 'ROCKET FIST', 24, 1.0), laser: M('laser', 'L', 'LASER EYES', 22, 1.0), kick: M('highkick', 'R', 'Hydraulic Kick', 20, 0.95), low: M('lowkick', 'L', 'Piston Low Kick', 13, 0.8), update: M('update', 'R', 'Firmware Update', 0, 3.2, { interrupt: false }) },
    ai: { jab: 3, jab2: 3, hook: 2, upper: 2, rocket: 2, laser: 2, kick: 1, low: 1, update: 0.6 }, combos: [['jab', 'jab2', 'rocket'], ['low', 'laser'], ['jab', 'hook', 'upper'], ['laser', 'rocket']],
    lines: {
      intro: ["GREETINGS, HUMAN. YOUR BEATING HAS BEEN SCHEDULED. PLEASE RATE IT 1 TO 5 STARS."],
      taunt: ["CALCULATING... YOUR CHANCE OF VICTORY: 0.0001%. ROUNDING DOWN.", "PLEASE HOLD. YOUR DEFEAT IS IMPORTANT TO US.", "ERROR 404: YOUR SKILL NOT FOUND.", "I HAVE STUDIED 10 MILLION FIGHTS. YOU ARE IN THE BOTTOM ONE.", "HAVE YOU TRIED TURNING YOUR FACE OFF AND ON AGAIN?"],
      hit: ["IMPACT CONFIRMED. LOL.", "HUMAN DAMAGE: SATISFACTORY.", "THAT WAS A FEATURE, NOT A BUG."],
      hurt: ["WARNING: FACE.EXE HAS STOPPED WORKING.", "OW. I MEAN: OUCH.WAV", "THIS WAS NOT IN THE PITCH DECK."],
      down: ["SYSTEM... REBOOTING... DO NOT... UNPLUG..."], win: ["VICTORY. UPLOADING YOUR TEARS TO THE CLOUD."],
      pattern: ["PATTERN DETECTED.", "PREDICTABLE HUMAN.", "I HAVE SEEN THAT ONE."],
    },
    corner: ["That tin can LEARNS. Mix it up — never throw the same thing three times in a row.", "Rocket fist: sidestep it. Lasers: duck under 'em. Don't block either one.", "When it does that update thing, beat on it before it finishes. Like my old laptop.", "It's the champ, kid. Dodge, counter, repeat. And maybe pray to the cloud."],
    interview: [['chet', "CAREY! YOU'RE THE CHAMPION OF THE WORLD! You beat a ROBOT! That's the craziest thing I've ever seen, and I once wrestled a bear! Allegedly!"], ['carey', "I unplugged him, Chet. The cord was right there."], ['barry', "The robot cried OIL! I never seen a computer get its feelings hurt! Oh my GOODNESS, champ!"], ['chet', "What's next for the new champion of the world?"], ['carey', "Sleep. Tacos. Then whoever's dumb enough to be next."], ['barry', "Somebody get this woman a belt AND a buffet!"]],
  },
];
ROSTER.forEach((r, i) => { r.idx = i; });
